<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Aspire.AppHost.Sdk" Version="9.1.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>aspire-MyNewLittleBank.AppHost</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\API\API.csproj" />
    <ProjectReference Include="..\Mock.Transactions\Mock.Transactions.csproj" />
    <ProjectReference Include="..\Services.Card\Services.Card.csproj" />
    <ProjectReference Include="..\Services.Heartbeats\Services.Heartbeats.csproj" />
    <ProjectReference Include="..\Services.Money\Services.Money.csproj" />
    <ProjectReference Include="..\Services.Pix\Services.Pix.csproj" />
  </ItemGroup>

</Project>
