version: "3.9"

name: mynewlittlebank

services:
  api:
    build:
      context: ../
      dockerfile: src/API/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=mynewlittlebank;Username=postgres;Password=postgres
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    restart: on-failure
    ports:
      - "5000:8080"
    networks:
      - bank-net

  mock-transactions:
    build:
      context: ../
      dockerfile: src/Mock.Transactions/Dockerfile
    environment:
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    restart: on-failure
    networks:
      - bank-net

  services-card:
    build:
      context: ../
      dockerfile: src/Services.Card/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=mynewlittlebank;Username=postgres;Password=postgres
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    restart: on-failure
    networks:
      - bank-net

  services-heartbeats:
    build:
      context: ../
      dockerfile: src/Services.Heartbeats/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=mynewlittlebank;Username=postgres;Password=postgres
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    restart: on-failure
    networks:
      - bank-net

  services-money:
    build:
      context: ../
      dockerfile: src/Services.Money/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=mynewlittlebank;Username=postgres;Password=postgres
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    restart: on-failure
    networks:
      - bank-net

  services-pix:
    build:
      context: ../
      dockerfile: src/Services.Pix/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=mynewlittlebank;Username=postgres;Password=postgres
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    restart: on-failure
    networks:
      - bank-net

networks:
  bank-net:
    external: true
    name: mynewlittlebank_bank-net
